# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='カテゴリ'),
        ),
    ]
